### ISSUE TITLE
Constantly rejected

### ISSUE THREAD

**Issue by hectorbarranca** [Deathspike/animesync#11]
Hi, since yesterday I had been contantly rejected after some download time, maybe it has some changes?
For example:
Fetching https://www.crunchyroll.com/es-es/tonikawa-over-the-moon-for-you
Fetching TONIKAWA Over The Moon For You 01 [CrunchyRoll].mkv
Rejected TONIKAWA Over The Moon For You 01 [CrunchyRoll].mkv (00:04:08)
Fetching TONIKAWA Over The Moon For You 02 [CrunchyRoll].mkv
Rejected TONIKAWA Over The Moon For You 02 [CrunchyRoll].mkv (00:04:08)
Fetching TONIKAWA Over The Moon For You 03 [CrunchyRoll].mkv
Rejected TONIKAWA Over The Moon For You 03 [CrunchyRoll].mkv (00:05:39)
Fetching TONIKAWA Over The Moon For You 04 [CrunchyRoll].mkv
Rejected TONIKAWA Over The Moon For You 04 [CrunchyRoll].mkv (00:04:48)
Fetching TONIKAWA Over The Moon For You 05 [CrunchyRoll].mkv
Rejected TONIKAWA Over The Moon For You 05 [CrunchyRoll].mkv (00:07:31)
Fetching TONIKAWA Over The Moon For You 06 [CrunchyRoll].mkv
Rejected TONIKAWA Over The Moon For You 06 [CrunchyRoll].mkv (00:05:19)
Fetching TONIKAWA Over The Moon For You 07 [CrunchyRoll].mkv
Rejected TONIKAWA Over The Moon For You 07 [CrunchyRoll].mkv (00:07:38)
Fetching TONIKAWA Over The Moon For You 08 [CrunchyRoll].mkv
Rejected TONIKAWA Over The Moon For You 08 [CrunchyRoll].mkv (00:07:22)
Fetching TONIKAWA Over The Moon For You 09 [CrunchyRoll].mkv

**Comment by hectorbarranca** [comment]
Also said:
{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
    at Socket.onChildStderr (child_process.js:377:14)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:265:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
  cmd:

... and more text but I thing maybe was by the buffer size

**Comment by hectorbarranca** [comment]
Sorry, solved xD was my error with the node version, I made some changes for another proyect and forgot that this project needs node >= 12

**Comment by Deathspike** [comment]
Great that you found the root cause and solved it. I'll make a note to add a warning.
