### ISSUE TITLE
Adding audio and subtitle flag for ffmpeg muxing options

### ISSUE THREAD

**Issue by Michelangelo1337** [Deathspike/animesync#14]
I noticed that after the muxing process is finish there is no language flag for the audio and subtitle in the mediainfo. 
I would suggest adding these options to ffmpeg if you are planning on supporting multi language subtitles.

**Comment by Deathspike** [comment]
Good point. Right now, audio language is always Japanese and subtitle language is always English.
It shouldn't be too hard to tag them appropriately, and it's a nice enhancement.
