### ISSUE TITLE
Help modifying library saving

### ISSUE THREAD

**Issue by Differentunic** [Deathspike/animesync#59]
I've tried to do it myself, but I can't seem to wrap my head around how everything runs together, but how would I go about converting the normal `animesync download` to something that downloads as an mp4 and saves the subtitles to the same location, as opposed to making an mkv with all the subtitles bundled.

Ive figured out how to change the code to save as an mp4 at the moment, but I cant figure out where the subtitles get deleted from the sync folder. 

EDIT: I only want to have it save with the library, because I want to use the API to check the library. I could use purely the API, but I wanted to be able to have the same file structure and all the thumbnails and .nfo files with it.

**Comment by Deathspike** [comment]
It is a little daunting. Here's a quick rundown of the project structure:

- `src/api`: Contains API call definitions and validations. Shared between both clients and the server.
- `src/client`: The web client hosted at `http://127.0.0.1:6583/web/`. It talks via the API to the server.
- `src/server`: The server. This is where the magic happens. This is what you're looking for.
- `src/shell`: The CLI client. It talks via the API to the server.
- `src/shell`: The unit tests. You probably don't care about this right now.

Zooming in a little further on the server, you'll see the following modules in there:

- `src/server/core`: Manages tunnels between `chrome` and `ffmpeg` to your proxy server.
- `src/server/library`: Library API calls. This manages the library and downloads. This is what you're looking for.
- `src/server/remote`: Remote API calls. This retrieves information from `crunchyroll` (and previously other providers, too).
- `src/server/rewrite`: Rewrite API calls. This rewrites HLS manifests (to proxy video file pieces) and subtitles (format, scaling).
- `src/server/setting`: Setting API calls. You probably don't care about this right now.
- `src/server/shared`: Functionality shared between modules (browser access, file access, logging, requests, etc).

That was a pretty long answer to tell you to look in `src/server/library`. This is what happens for a download request:

1. A HTTP request comes in [LibraryController](https://github.com/Deathspike/animesync/blob/v2.1.0/src/server/library/LibraryController.ts#L114). This is delegated to `LibraryService`.
2. The request goes to [saveEpisodeAsync](https://github.com/Deathspike/animesync/blob/f2889be1297eeb9c7044c01e7c73e8b608b1ae6c/src/server/library/services/LibraryService.ts#L133). This uses a supervisor to ensure the episode can't download twice in parallel.
3. A [Runner](https://github.com/Deathspike/animesync/blob/f2889be1297eeb9c7044c01e7c73e8b608b1ae6c/src/server/library/classes/Runner.ts#L32) then executes for the episode. Here, `ffmpeg` is invoked to download. Internally, it uses rewritten manifests.
4. The [Runner](https://github.com/Deathspike/animesync/blob/f2889be1297eeb9c7044c01e7c73e8b608b1ae6c/src/server/library/classes/Runner.ts#L53) then creates and runs a [SubtitleBundler](https://github.com/Deathspike/animesync/blob/f2889be1297eeb9c7044c01e7c73e8b608b1ae6c/src/server/library/classes/SubtitleBundler.ts). This creates a `.zip` file with subtitles for quick access by API. 

I would recommend you modify that `SubtitleBundler` to move the subtitle files to the episode output directory instead. Then you will have your `.mp4` with associated subtitles next to them. If you're then intent to use the API to access the subtitles as well, you'll have to change the way that API works. For that, change the way [episodeSubtitleAsync](https://github.com/Deathspike/animesync/blob/f2889be1297eeb9c7044c01e7c73e8b608b1ae6c/src/server/library/services/LibraryService.ts#L125) works to bundle your subtitles on-the-fly and you have to remove the [SubtitleService](https://github.com/Deathspike/animesync/blob/f2889be1297eeb9c7044c01e7c73e8b608b1ae6c/src/server/library/services/SubtitleService.ts) to prevent it from trying to re-create subtitle `.zip` files.
